### PR TITLE
Conda build for all platforms

### PR DESCRIPTION
**Pull request by anton-matosov**
I have ported library to latest boost and implemented conda package build scripts to have fully contained distribution. I have also altered examples a little bit to make them suitable as smoke tests.
Supported configurations:
 - linux-x64: py27, py35, py36
 - osx-x64: py27, py35, py36
 - win-32: py35, py36
 - win-64: py35, py36

I couldn't build library on Windows for python 2.7 because it uses super old compiler from VS2008 that doesn't support C++11 features. So this configuration is not supported.

This PR also includes complete CI setup for all these configurations.
For Linux and OSX it uses Travis-CI
For Windows - Appsveyor

Configuration environment variables:
- `CONDA_UPLOAD` - whether to upload package to anaconda.org. possible values: `yes` or `no`
- `CONDA_LOGIN_USERNAME` - username on anaconda.org to upload package to
- `CONDA_LOGIN_PASSWORD` - password on anaconda.org to upload package to 

In future I want to submit it as feedstock to conda-forge to make re-distribution easy.
Currently packages are available from my personal channel with boost from conda-forge:
`conda install multineat -c anton.matosov -c conda-forge`

### CODE REVIEW

**Comment by winycg** [comment]
Great！We will be easy to install the multineat library without building the 'MultiNEAT-master' file,so it can make the install process more smooth!I will support and pay close attention to the library continuously.

**Comment by Riseley** [comment]
We need this.

**Comment by peter-ch** [comment]
It says these files are conflicting:
src/NeuralNetwork.cpp
src/NeuralNetwork.h
src/PythonBindings.h

**Comment by anton-matosov** [comment]
Ok, I will take a look

**Comment by anton-matosov** [comment]
I have fixed all the conflicts

**Comment by peter-ch** [comment]
Thanks!

**Pull request merged**
